workflows:
  ios-workflow:
    name: iOS Workflow
    integrations:
      app_store_connect: BallPaint Raid
    environment:
      ios_signing:
        distribution_type: app_store
        bundle_identifier:
          - ball.paintra.id
          - ball.paintra.id.pe
      vars:
        XCODE_PROJECT: "PaintRaid.xcodeproj"
        XCODE_SCHEME: "PaintRaid"
        APP_STORE_APPLE_ID: 6745492366
      xcode: latest
    triggering:
      events:
        - push
        - tag
        - pull_request
      branch_patterns:
        - pattern: 'release'
          include: true
          source: true
    scripts:
      - name: Increment build number
        script: |
          agvtool new-version -all $(($(app-store-connect get-latest-testflight-build-number "$APP_STORE_APPLE_ID") + 1))
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa --project "$XCODE_PROJECT" --scheme "$XCODE_SCHEME"
    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        expire_build_submitted_for_review: false
        beta_groups:
          - group name 1
          - group name 2
        submit_to_app_store: false
      email:
        recipients:
          - user1@example.com
          - user2@example.com
        notify:
          success: true
          failure: true
      slack:
        channel: '#builds'
        notify_on_build_start: true
        notify:
          success: false
          failure: false
